version: '2'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${HTTP_PORT:-80}:80
    links:
      - php
  php:
    build: ./docker/php
    depends_on:
      - mariadb
    volumes:
      - ./app:/var/www/html
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - ./db-data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT:-3306}:3306
  phpmyadmin:
    image: phpmyadmin
    ports:
      - ${PMA_PORT:-8081}:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
